# alpine-1.30.0
# https://hub.docker.com/layers/denoland/deno/alpine-1.30.0/images/sha256-8a287de2bea72037974dc021c94f783142d6cdea1d738b571104a242af364200?context=explore
FROM denoland/deno@sha256:8a287de2bea72037974dc021c94f783142d6cdea1d738b571104a242af364200
RUN apk add curl zip

# install just
RUN cd tmp \
    && curl --silent --show-error --fail --location --output just.tar.gz https://github.com/casey/just/releases/download/1.12.0/just-1.12.0-x86_64-unknown-linux-musl.tar.gz \
    && tar xfz just.tar.gz \
    && mv /tmp/just /usr/bin/just

ADD . /pgs-to-srt
CMD cd pgs-to-srt && just ci
