# alpine-1.30.2
# https://hub.docker.com/layers/denoland/deno/alpine-1.30.2/images/sha256-1c6f5768a1d8213d40e0728b7f8b3a62cd470c085c959c1c0a832491a5f1398a?context=explore
FROM denoland/deno@sha256:1c6f5768a1d8213d40e0728b7f8b3a62cd470c085c959c1c0a832491a5f1398a
RUN apk add curl zip npm

# install just
RUN cd tmp \
    && curl --silent --show-error --fail --location --output just.tar.gz https://github.com/casey/just/releases/download/1.12.0/just-1.12.0-x86_64-unknown-linux-musl.tar.gz \
    && tar xfz just.tar.gz \
    && mv /tmp/just /usr/bin/just

ADD . /pgs-to-srt
CMD cd pgs-to-srt && just ci
